---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-boot-docker
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-boot-docker
                port:
                  number: 8080

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: spring-boot-docker
  name: spring-boot-docker
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: spring-boot-docker

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-docker
  template:
    metadata:
      labels:
        app: spring-boot-docker
    spec:
      containers:
        - name: spring-boot-docker
          image: itstarting/spring-boot-docker
          ports:
            - containerPort: 8080
